version: "3"

services:
  serverbe:
    command: npm run dev
    container_name: serverbe
    build: ./server
    ports:
      - "3000:3000"
  clientfe:
    depends_on:
      - serverbe
    container_name: clientfe
    build: ./client
    ports:
      - "80:80"
